[package]
name = "md_web_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
pulldown-cmark = "0.9.0"
tokio = { version = "1", features = ["full"] }
